[theme.light]
primaryColor = "#950E29"
backgroundColor = "#faf9f6"
secondaryBackgroundColor = "#ecebe3"
textColor = "hsl(9, 18%, 20%)"
linkColor = "hsl(9, 18%, 20%)"
borderColor = "hsl(9, 10%, 71%)"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]
chartSequentialColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.dark]
primaryColor = "#c8352d"
backgroundColor = "#141414"
secondaryBackgroundColor = "#171717"
textColor = "#d5cac3"
linkColor = "#d5cac3"
borderColor = "#352d2c"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#1b1a13"
showSidebarBorder = true
chartCategoricalColors = ["hsl(199, 89%, 52%)", "hsl(161, 94%, 70%)", "hsl(43, 96%, 44%)"]
chartSequentialColors = ["hsl(199, 89%, 52%)", "hsl(161, 94%, 70%)", "hsl(43, 96%, 44%)"]