[theme.light]
primaryColor = "#945ccc"
backgroundColor = "#f9f9eb"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#bcbaae"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true
chartCategoricalColors = ["#0ea5e9", "#059669", "#fbbf24"]
chartSequentialColors = ["#0ea5e9", "#059669", "#fbbf24"]

[theme.dark]
primaryColor = "#9e6cd0"
backgroundColor = "#141414"
secondaryBackgroundColor = "#17131b"
textColor = "#d5d2c3"
linkColor = "#d5d2c3"
borderColor = "#35342c"
showWidgetBorder = true
baseRadius = "0.75rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#1b1a13"
showSidebarBorder = true
chartCategoricalColors = ["hsl(199, 89%, 52%)", "hsl(161, 94%, 70%)", "hsl(43, 96%, 44%)"]
chartSequentialColors = ["hsl(199, 89%, 52%)", "hsl(161, 94%, 70%)", "hsl(43, 96%, 44%)"]